# -*- coding: utf-8 -*-
"""EDA_for_Tournament_Data_Preparation_and_Insights

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eMYmNy3ObX6VkCMzILKlKKHxyoNC6760
"""

import requests
import pandas as pd
import os

df = pd.read_excel(r"/content/sample_data/Input/Bangalore Cricket Tournament(1-137) (1).xlsx")

try:
    output_dir = r"/content/sample_data/Output/"
    output_path = os.path.join(output_dir, "Bangalore_Cricket_Tournament.csv")

    os.makedirs(output_dir, exist_ok=True)

    df.to_csv(output_path, index=False) # Changed 'df' to 'csv_team'
    print(f"Successfully saved to {output_path}")

except Exception as e:
    print(f"File Error: {e}")

csv_team = pd.read_csv(r"/content/sample_data/Output/Bangalore_Cricket_Tournament.csv")
csv_team.head()

print(f"Null values in 'Last modified time': {csv_team['Last modified time'].isnull().sum()}")

# Drop the 'Last modified time' column
csv_team_drop_column = csv_team.drop(columns=['Last modified time', 'Name2'])
print(f"After dropping the unnecessary column")
csv_team_drop_column.head()

"""# Task
Filter the 'csv_team_filtered' DataFrame to select the first 105 male entries and the first 15 female entries, sort each group by 'Start time' in ascending order, combine them into a new DataFrame called `scheduled_team`, and then display the head of `scheduled_team` along with a confirmation message.

**Reasoning**:
Filter the 'csv_team_drop_column' DataFrame to include only male and female entries, sort them by 'Start time', and select the first 105 rows as instructed in the subtask.
"""

male_participants = csv_team_drop_column[csv_team_drop_column['GENDER'] == 'M'].sort_values(by='Start time', ascending=True).head(105)
print("First 105 male participants sorted by 'Start time':")
display(male_participants)

female_participants = csv_team_drop_column[csv_team_drop_column['GENDER'] == 'F'].sort_values(by='Start time', ascending=True).head(15)
print("First 15 female participants sorted by 'Start time':")
display(female_participants)

"""**Reasoning**:
Combine the `male_participants` and `female_participants` DataFrames into a new DataFrame called `scheduled_team`, and then display its head along with a confirmation message as per the subtask requirements.


"""

scheduled_team = pd.concat([male_participants, female_participants])
print("Combined Male and Female Participants (scheduled_team):", len(scheduled_team))
scheduled_team.head()

import matplotlib.pyplot as plt
import seaborn as sns

gender_counts = scheduled_team['GENDER'].value_counts()

# Convert the Series to a DataFrame for heatmap
gender_counts_df = gender_counts.to_frame(name='Count')


plt.figure(figsize=(8, 6))
plt.title('Distribution of Genders in Scheduled Team (Bar Plot)')
plt.xlabel('Gender')
plt.ylabel('Count')
sns.barplot(x=gender_counts_df.index,
            y=gender_counts_df['Count'],
            hue=gender_counts_df.index,
            palette='viridis',
            legend=False)

plt.show()

final_path = r"/content/sample_data/Output/blr_cricket_tournament_data_eda.json"

scheduled_team.to_json(os.path.join(final_path))
print(f"Successfully saved scheduled_team to {final_path}")

"""## Summary:

### Data Analysis Key Findings
*   Successfully created a `male_participants` DataFrame containing the first 105 male entries from `csv_team_drop_column`, sorted by 'Start time' in ascending order.
*   Successfully created a `female_participants` DataFrame containing the first 15 female entries from `csv_team_drop_column`, sorted by 'Start time' in ascending order.
*   The `scheduled_team` DataFrame was accurately constructed by concatenating the `male_participants` and `female_participants` DataFrames, resulting in a combined set of 120 entries (105 male and 15 female) each sorted by 'Start time' within their respective groups.

### Insights or Next Steps
*   The `scheduled_team` DataFrame is now prepared according to specific gender and quantity requirements, making it ready for scheduling or allocation purposes.
*   Further analysis could involve examining the 'Start time' distributions within the `scheduled_team` to identify any potential biases or clustering in the assigned times.

"""

# To rename this Colab notebook file, click on the file name at the top-left corner of the interface and type in your desired name.